---
- name: Configure zookeeper-env.sh
  template: src=zookeeper-env.sh.j2 dest={{ zookeeper_dir }}/conf/zookeeper-env.sh owner=zookeeper group=zookeeper
  tags: deploy
  notify:
    - Restart zookeeper
  when: zookeeper_env is defined and zookeeper_env|length > 0

- name: Start zookeeper service
  service: name=zookeeper state=started enabled=yes
  tags: deploy

- name: Build zkinit script
  lineinfile:
    dest: "{{zookeeper_dir}}/conf/zkinit"
    regexp: ' {{ item }} '
    line: "create {{item}} []"
    state: present
    create: yes
    owner: zookeeper
    group: zookeeper
  tags: deploy
  notify:
    - Run zkinit script
  when: zookeeper_chroots is defined
  with_items: "{{zookeeper_chroots}}"
