---
- name: Restart zookeeper
  service: name=zookeeper state=restarted enabled=yes

- name: Reload systemctl daemon
  command: systemctl daemon-reload
  when: ansible_service_mgr == 'systemd'

- name: Run zkinit script
  shell: "sleep 5; {{zookeeper_dir}}/bin/zkCli.sh <{{zookeeper_dir}}/conf/zkinit -server localhost:{{client_port}}"
